import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

[env]
INIT_X11_SCALE_FACTOR = "1.0"
WTERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 5

[scrolling]
multiplier = 5

[font]
normal = { family = "JetBrains Mono Nerd Font", style = "Regular" }
bold = { family = "JetBrains Mono Nerd Font", style = "Bold" }
italic = { family = "JetBrains Mono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrains Mono Nerd Font", style = "Bold Italic" }
size = 8

[shell]
program = "/usr/bin/zsh"
args = ["-c", "neofetch; exec zsh"]
